version: '3.3'
services:
  db:
    container_name: pizzi_db
    image: postgres:latest
    restart: always
    volumes:
      - pizzi-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - rsc-server-tier
      - auth-server-tier
      - db-tier

  db-migration:
    container_name: pizzi_db_migration
    image: pizzi-db-migration
    restart: "no"
    volumes:
      - ./PizziDeploy/config.json:/etc/PizziMigration/config.json
    networks:
      - db-tier

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: on-failure
    ports:
      - 8465:8465
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    volumes:
      - pizzi-pgadmin-data:/var/lib/pgadmin
    networks:
      - db-tier

  rsc-server:
    container_name: pizzi_rsc_server
    image: pizzi-rsc-runner
    restart: on-failure
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:5000"
    networks:
      - rsc-server-tier

  auth-server:
    container_name: pizzi_auth_server
    image: pizzi-auth-runner
    restart: on-failure
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3001:3000"
    networks:
      - auth-server-tier

volumes:
  pizzi-db-data:
  pizzi-pgadmin-data:

networks:
  rsc-server-tier:
  auth-server-tier:
  db-tier:
